### ISSUE TITLE
It doesn't seem to be successful.

### ISSUE THREAD

**Issue by XBisATrouble** [touchfluffytails/Palworld-Palbox-Slot-Injector#1]
➜  Palworld-Palbox-Slot-Injector git:(main) ✗ python3 inject_box_slots.py Level_fixed.sav.json

Working on Level.sav.json from: Level_fixed.sav.json
Opened script at: /Users/xx/Palworld-Palbox-Slot-Injector
Configured Pal box count: 32
Configured Pal box slot count: 30
Desired total slot count is: 960
Getting player saves...
0 players with json dumped for this world
Getting player pal boxes...
Getting blank slot template...
Loaded following file as blank slot template: /Users/xx/Palworld-Palbox-Slot-Injector/blankpalslot.json
Loading level save...
Getting all known player pal box structures...
Injecting blank slots to player pal boxes to size 960...
Backing up previous level.sav.json...
Dumping new level.sav.json...

Pal box slots injected into 0 player pal boxes

**Comment by touchfluffytails** [comment]
Script works by needing to read the .sav.json for players savs in the Players folder. Could you confirm if you've ran all your player saves through the save-tool first?

I threw up an update to add some guardrails for this to give more useful output when it doesn't find any dumped player savs
