### ISSUE TITLE
No in-game changes

### ISSUE THREAD

**Issue by Dr-WeiAL** [touchfluffytails/Palworld-Palbox-Slot-Injector#2]
```
Working on Level.sav.json from: C:\Users\WeiAL\Desktop\5FCEEF154A7E4548564696B12C3D04FA\Level.sav.json
Opened script at: C:\Users\WeiAL\Desktop\Tool\Palworld-Palbox-Slot-Injector
Configured Pal box count: 32
Configured Pal box slot count: 30
Desired total slot count is: 960
Getting player saves...
3 players with json dumped for this world
Getting player pal boxes...
Getting blank slot template...
Loaded following file as blank slot template: C:\Users\WeiAL\Desktop\Tool\Palworld-Palbox-Slot-Injector\blankpalslot.json
Loading level save...
Getting all known player pal box structures...
Injecting blank slots to player pal boxes to size 960...
Backing up previous level.sav.json...
Dumping new level.sav.json...

Pal box slots injected into 3 player pal boxes
```

It looks like it worked, but it's still 16 pages in-game
![image](https://github.com/touchfluffytails/Palworld-Palbox-Slot-Injector/assets/47446553/2f84a0b7-3ac2-4e5f-a315-3ec86ed3a8db)

**Comment by Dr-WeiAL** [comment]
At the moment it looks like the dedicated server can't use RE-UE4SS, so it's temporarily shut down

**Comment by touchfluffytails** [comment]
I believe you can run RE-UE4SS on dedicated with https://github.com/N00byKing/PalWorld-ServerInjector but I haven't tested this myself so I can't confirm if it'd work.

**Comment by Dr-WeiAL** [comment]
I tried it, it doesn't work, it's not updated, it says in issues that it's version 1.2.0, so 1.3.0 won't work
https://github.com/N00byKing/PalWorld-ServerInjector/issues/8

**Comment by touchfluffytails** [comment]
Seems like it may be related to the signature used? Something I saw earlier but https://www.nexusmods.com/palworld/users/63907421?tab=user+files latest mods appear to have alongside them an updated signature you could replace the injectors with.

**Comment by Dr-WeiAL** [comment]
Okay, thanks. I'll try it later.

**Comment by Dr-WeiAL** [comment]
![image](https://github.com/touchfluffytails/Palworld-Palbox-Slot-Injector/assets/47446553/4621eb42-fc4e-491f-a523-b4832ca81354)
It worked. Thank you very much.
