### ISSUE TITLE
Not provided level.sav.json Press any key to continue . . .

### ISSUE THREAD

**Issue by Chillaya** [touchfluffytails/Palworld-Palbox-Slot-Injector#3]
I think I follow all the How to use:

<img width="206" alt="image" src="https://github.com/touchfluffytails/Palworld-Palbox-Slot-Injector/assets/158236865/ce7f9198-0494-49e4-a291-dd6530e197e7">

and I already have .json files of both Level and Player file.
<img width="520" alt="image" src="https://github.com/touchfluffytails/Palworld-Palbox-Slot-Injector/assets/158236865/ebd53d07-96cc-45ea-8b57-c3860503cbfc">
<img width="532" alt="image" src="https://github.com/touchfluffytails/Palworld-Palbox-Slot-Injector/assets/158236865/9a78c1bb-5ae8-43e8-a6c8-62fd738c8457">

And the instructions isn't clear enough on how to use it.
I change slot from normal to 64 pages and 30 slots

Do I have to install "Bigger and Reorganized PalBox" ?
If "YES" .... the rest of the page is blank.
If "No" ....I don't have more pages and more slots.

Am I did something wrong?

**Comment by touchfluffytails** [comment]
The inject_box_slots.cmd works the same as Palworld-Save-Tools. You need to drag the Level.sav.json onto it for it to work.
If it isn't working despite you doing this, I've updated the script to hopefully give better error messages for arguments passed in. So try with that and see if it solves the problem for you.

"Bigger and Reorganized PalBox" only works on existing characters when the script is succesful. Until it is, it will display empty extra boxes as there is no data in the sav for it to display. I updated the readme however to try and better explain what needs to be done with "Bigger and Reorganized PalBox" after the script has been ran.

**Comment by Chillaya** [comment]
> The inject_box_slots.cmd works the same as Palworld-Save-Tools. You need to drag the Level.sav.json onto it for it to work. If it isn't working despite you doing this, I've updated the script to hopefully give better error messages for arguments passed in. So try with that and see if it solves the problem for you.
> 
> "Bigger and Reorganized PalBox" only works on existing characters when the script is succesful. Until it is, it will display empty extra boxes as there is no data in the sav for it to display. I updated the readme however to try and better explain what needs to be done with "Bigger and Reorganized PalBox" after the script has been ran.

I have try to drag the flie to the inject_box_slots.cmd, but the cmd just disappeared and there is nothing happened.

First, when I try to run the inject_box_slots.cmd it said Not Provideed level.sav.json. and I try to drag the file to the cmd. and that what it was happened. I don't know why. I try to figure this out.

**Comment by touchfluffytails** [comment]
I've updated the script with a UI. Try the latest version and see how it goes

**Comment by touchfluffytails** [comment]
If you still need assistance try the latest version and reply otherwise I'm closing this.

**Comment by touchfluffytails** [comment]
If you still need assistance try the latest version and reply if it doesn't work. Otherwise I'm closing this.
