### ISSUE TITLE
python not installed?

### ISSUE THREAD

**Issue by BlownBigBen** [touchfluffytails/Palworld-Palbox-Slot-Injector#6]
i try to run the script and get this error. i do have python and save editor installed.
![python error](https://github.com/touchfluffytails/Palworld-Palbox-Slot-Injector/assets/156870991/1134c3ba-50b0-4407-a076-2ad4b66dad50)

**Comment by touchfluffytails** [comment]
If you still need assistance try the latest version and reply if it doesn't work. Otherwise I'm closing this.
